language: node_js
node_js:
  - '7'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
before_script: node ./scripts/tag-update $TRAVIS_TAG
# after_success: npm run cover
before_deploy: npm run prepare-github-pages
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: alisahinozcelik@gmail.com
    api_key:
      secure: nPBjAuA/O60Fc8L6+fBQJ450TMCUnvie/VqpQJelNH0YPZGM6Wq5c7XV2xDdtEdhrkBRA0VEN4Rihn8C5OLh/uvu53dqfEoi4HEoafG6/uYaOQA9nB1kegqoiEGbJkHcEApd1uKBOkOpKAYfVwpYTFPnDJAbafN+OaQgQlcqKkYgH+VVcopfy/orLjq7s78zr7PRKdD0tbSPJtOFcX5zLhYAIMZpN5sk2tFEKQAUqLH0DPkxcYcjyXcxnSWq8TJYc2EeooKkqijAIl1NOT2NLdTRGa2SQ/XrdbM0CRCDZa19OI3q7eQayzsFfO0OGC5hbvoiKipAxqDUMkxmiUNymMknUflkJUbU7GOKyqGE9oDPLcMxU1RDaXXMw9WkyZ2k/StBEG8i5vre4Vd9pFavoMNYXigBUACl/dudg7M/qjmHQImJZ2IU8Isvjl2Y/Qjo/SvKTJqgEumr9V2le46B2tRp5ec7X7ghx081DPVOc4W0buaC9DD7xY+gjJ4HFJ5b34S+lhjMNfu2ZTt/yglkDkrnm4vn0pVlowRTww07A3vFAqZsDpp/B/qcMOH4N+8mgYUzJNQppAa2qXb1utNqk2TD0TP4SJskrGl6QCH/7fBBXNHMEDwPX35brWV4hle/vAwSIaR/4KYDm+K12pH2UeHQBzm5AWXIpst4qYi8iCI=
    on:
      tags: true
      repo: gen-tech/sticky
